### ISSUE TITLE
Create Hydrodynamics Plugin for Gazebo Using Rigid-Body Hydrodynamics and Hydrostatics

### ISSUE THREAD

**Issue by loganfillo** [ubc-subbots/triton#18]
We need to create a hydrodynamic force plugin for gazebo to act on the AUV. This plugin should be a Gazebo model plugin, and during its OnUpdate() function, it should apply the hydrodynamic forces found in Fossen's AUV model to the Gazebo model based on it's current state. Right now we should only worry about applying hydrostatic forces (i.e gravitational forces or g(eta)) and rigid body hydrodynamic forces (i.e mass/inertia matrix and coriolis matrix or M_RB*nu_dot + C_RB(nu)*nu).See the resources for the simplified equations. Further issues will be about adding the damping forces and added mass forces.

**Resources**
[Model Plugins Tutorial](http://gazebosim.org/tutorials?tut=plugins_model&cat=write_plugin)
[Equations](https://shodhganga.inflibnet.ac.in/bitstream/10603/126187/17/12_chapter3.pdf) - See pg.43 for the rigid body hydrodynamics equations, and pg.47 for the hydrostatic equations
[Gazebo Model API](http://osrf-distributions.s3.amazonaws.com/gazebo/api/11.0.0/classgazebo_1_1physics_1_1Model.html) - See GetLink()
[Gazebo Link API](http://osrf-distributions.s3.amazonaws.com/gazebo/api/11.0.0/classgazebo_1_1physics_1_1Link.html) - See AddForce(), AddTorque(), WorldPose(), RelativeAngularVel(), RelativeLinearVel(), RelativeAngularAccel(), RelativeLinearAccel(), 
[Ignition Math API](https://ignitionrobotics.org/api/math/6.6/index.html)

**Notes**
- This is how I see the plugin working. The plugin will be a child of the model tag, and have a child tag "link_name" as a parameter. The Load() function will read this "link_name" and expect it to be a child of the model tag, and produce an error if not. Once it has the link  specified in "link_name" (which has all the model param info like mass/inertia/cog/cob etc.), it can read those values, and also the state of the base link in the OnUpdate(), and construct the equations needed. Then it can add the forces the equations produce onto the base link and wait til the next iteration of OnUpdate() is called to do the procedure all over again.

- [x] Create the Gazebo plugin and ensure that it builds and can be used in a model

- [x] Implement the hydrostatics forces in the OnUpdate() method, use teleop controls and play around with the worlds and models to verify it works

- [x] Implement the rigid body hydrodynamics forces in the OnUpdate() method, verify as above

**Comment by JakeCronin1997** [comment]
Implemented plugin merged with logan/issue18
