### ISSUE TITLE
Investigate coordinate system transform when importing, Seperate Robot components

### ISSUE THREAD

**Issue by JakeCronin1997** [ubc-subbots/triton#38]
Investigate coordinate system transformation between SolidWorks and Gazebo.Modify triton_auv to have robot frame and thrusters as separate models and decrease the resolution of models to allow Gazebo to run better

**Comment by JakeCronin1997** [comment]
Coordinates seem to be correct when importing, would be good to make sure solidworks models are correctly orientated before importing.

**Comment by JakeCronin1997** [comment]
Decreasing model resolution can be done very effectively in Gazebo

**Comment by loganfillo** [comment]
74 closes this
