### ISSUE TITLE
Change triton_pipeline to Detect all Pipeline Types Without User Configuration

### ISSUE THREAD

**Issue by loganfillo** [ubc-subbots/triton#5]
We need to change the way `pipeline_manager` identifies the pipeline types available so that a user creating a new pipeline never has to modify the node. The pipeline types are given by `PipelineTypes.msg` in `triton_interfaces`, and the init function of `pipeline_manager` needs to be able to store all types given in that message at runtime. 

**Tasks**

- [x] Modify `pipeline_manager` so that all pipeline types are discovered and stored in the init function 

- [x] Test this by creating a dummy type in `PipelineTypes.msg` and a corresponding config file in the `tr_pipeline` package and test that the dummy type is correctly identified and the associated config file can be used to configure the pipeline.

**Comment by Over-TheRainbow** [comment]
Should I put it on a new branch?

**Comment by loganfillo** [comment]
> Should I put it on a new branch?

Sorry just saw this, yes you can do a similar convention to what we have done in the past "andrew/Issue5" so that the branch refers to the issue

**Comment by loganfillo** [comment]
Done see #13
