### ISSUE TITLE
Write test suite for pipeline_manager

### ISSUE THREAD

**Issue by loganfillo** [ubc-subbots/triton#9]
We need to write a test suite for the pipeline manager to ensure it acts correctly. Below are the test cases we need to test.

misc
- [x] Change the launch file name from `triton_pipeline.launch.py` to `pipeline.launch.py`, and edit the appropriate `setup.py` and `README.md` files. (I think this is a better convention, we only need the `triton` prefix in packages)

init
- [x] If pipeline_manager node is launched without a components_container, it should hang in the init function (might need to add a log statement at end of init to be able to justify that it hangs)

configure_pipeline
- [x] If pipeline_manager node configure pipeline service is used with a pipeline type that doesn't exist, the service call should be unsuccessful

- [x] If pipeline_manager node configure pipeline service is used with a pipeline type that does exist, but the yaml does not exist with the same name as the pipeline type, the service call should be unsuccessful

- [x] If pipeline_manager node configure pipeline service is used with a pipeline type that does exist, but the yaml associated to the type is ill formatted, the service call should be unsuccessful

- [x] If pipeline_manager node configure pipeline service is used with a pipeline type that does exist, the yaml is well formatted, but does not contain the pipeline paramter namespace, the service call should be unsuccessful

- [x] If pipeline_manager node configure pipeline service is used with a pipeline type that does exist, the yaml is well formatted with pipeline namespace, but either it contains a parameter that doesn't exist, the service call should be unsuccessful

- [x] If pipeline_manager node configure pipeline service is used with a pipeline type that does exist, the yaml is well formatted with pipeline namespace, but one of parameters has an invalid type, the service call should be unsuccessful

- [x] If pipeline_manager node configure pipeline service is used with a pipeline type that does exist, the yaml is well formatted with pipeline namespace, but the length of component and package name arrays are not equal the service call should be unsuccessful

run_pipeline

- [x]  If pipeline_manager node run pipeline action is called without the pipeline being configured, the action should be aborted (this is not implemented, you will have to implement it)

- [x] If pipeline_manager node run pipeline action is used on a configured pipeline but the config file used to configure the pipeline contains a pkg_name that is not a valid package, the action should be aborted (this is not implemented, you will have to implement it)

- [x] If pipeline_manager node run pipeline action is used on a configured pipeline but the config file used to configure the pipeline contains a pkg_name, component_name pair such that component_name is not a component in pkg_name, the action should be aborted (this is not implemented, you will have to implement it)

**Comment by Over-TheRainbow** [comment]
What should I check for:
"If pipeline_manager node configure pipeline service is used with a pipeline type that does exist, the yaml is well formatted, but does not contain the pipeline paramter namespace, the service call should be unsuccessful"?

The pipeline manager can create a warning 'Pipeline config YAML needs pipeline namespace', but it does not check do a specific test.
That message is currently supposed to appear if pipeline_params is None. Should I instead create a different message there, and after loading params try to check if namespace was loaded?

**Comment by loganfillo** [comment]
@Over-TheRainbow  If you look at one of the config files, under `ros__parameters:` there should be a line `pipeline:` which is a namespace for the parameters needed for the pipline. If this `pipeline:` didn't exist then the yaml parser would not be able to find the pipeline parameters and pipeline_params would be None. 

One more thing, I think to avoid clutter in the PipelineType.msg, we should just use the "example" type as the type in all the test cases,  and just use the config file name param to specify which yaml the test should be using. For the missing yaml case, just use a config file name that doesn't exist and it should execute the same logic. Also if you end up reusing most of the code for each test case, it might help to encapsulate that in a helper function to avoid repeatability

**Comment by Over-TheRainbow** [comment]
For 
"If pipeline_manager node configure pipeline service is used with a pipeline type that does exist, the yaml is well formatted with pipeline namespace, but one of parameters has an invalid type, the service call should be unsuccessful",
do you know if there is a log message that is printed already for this case? If there isn't, how should I compare the parameters to to check their type? Should I just check if they are strings / lists of strings according to the where the parameters are declared in the constructor?

**Comment by loganfillo** [comment]
Weird, it looks like it hangs when trying to set a parameter of an incorrect type. I suggest the following; in _create_param_object, when you get the param_type from the curr_val, also get the type of the value to set (param_val), and make sure these types are equal, otherwise throw an exception or change the logic so that _load_params_from_yaml will return false in this case. Make sure to also print a message when this happens. Check out the [source code for  rclpy parmeters](https://github.com/ros2/rclpy/blob/master/rclpy/rclpy/parameter.py) for further understanding of how parametrs work.

**Comment by Over-TheRainbow** [comment]
I'm a bit confused how to test the _load_component function to not load a component successfully. I tried using a test yaml with two components with the same name, but it was successfully loaded, though it did complain a bit. Not sure how to get it to be unsuccessful, do you have anything that I could try?

**Comment by loganfillo** [comment]
@Over-TheRainbow  Sorry I just saw this. You should be able to load the same component multiple times (i.e load two example::ComponentOne nodes) but right now the node_name is static so it will be the same and that's why it complains. The main cause of the load_components not working is if you give it a component that simply doesn't exist (i.e example::DoesNotExist). The point in the code where you should see that the load_component failed is where we check "if not res.success", then log the warning. Basically what we want to do is make sure that the warning is printed when a config file contains a component that isn't in the corresponding package, or a package doesn't exist. An example config file for the first case could look like 

pipeline_manager:
  ros__parameters:
    pipeline:
      components:
        - example::DoesNotExist # this component is not in the package
      pkg_names: 
        - triton_example
      namespace: /triton/example
      remap_rules:
        - /triton/example/component_two/in:=/triton/example/component_one/out
    use_sim_time: false

and for the second case
pipeline_manager:
  ros__parameters:
    pipeline:
      components:
        - example::ComponentOne
      pkg_names: 
        - triton_does_not_exist   # package doesn't exist
      namespace: /triton/example
      remap_rules:
        - /triton/example/component_two/in:=/triton/example/component_one/out
    use_sim_time: false

**Comment by Over-TheRainbow** [comment]
I just wanted to check if the output for your second case is correct. I was surprised to see that it aborted with a message that it failed to load **example::ComponentOne**, but it makes sense to me that it couldn't load the component because it had a non-existent package. This should be good output right? Or should it be changed?

**Comment by loganfillo** [comment]
@Over-TheRainbow I am not sure exactly what the message should be, but to find out, use the CLI component interface to do some test commands and see what they produces. Behind the scenes, the CLI is calling the same service we are: https://index.ros.org/doc/ros2/Tutorials/Composition/
